version: '3.9'

services:
  service-discovery:
    container_name: service-discovery
    build: ./service-discovery
    image: service-discovery:latest
    ports:
      - "9080:9080"
    healthcheck:
      test: "curl --fail --silent localhost:9080/actuator/health | grep UP || exit 1"
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 2s

  team-service:
    container_name: team-service
    build: ./team-service
    image: team-service:latest
    depends_on:
      service-discovery:
        condition: service_healthy
    ports:
      - "9090:9090"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-discovery:9080/eureka

  players-service:
    container_name: players-service
    build: ./players-service
    image: players-service:latest
    depends_on:
      service-discovery:
        condition: service_healthy
    ports:
      - "9091:9091"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-discovery:9080/eureka

  api-gateway:
    container_name: api-gateway
    build: ./api-gateway
    image: api-gateway:latest
    depends_on:
      service-discovery:
        condition: service_healthy
    ports:
      - "9000:9000"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-discovery:9080/eureka