server:
  port: 9091
  servlet:
    context-path: /rest/player

spring:
  application:
    name: players-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/football_data_db
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9080/eureka/
    registerWithEureka: true
    fetchRegistry: true

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"

springdoc:
  api-docs:
   path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true