openapi: 3.0.1
info:
  description: Player REST API
  title: Player REST API
  version: 1.0.0
servers:
  - url: http://localhost:9091

paths:
  /players/{id}:
    get:
      description: Get player identified by the id

      parameters:
        - in: path
          name: id
          required: true
          schema:
            format: string
            type: string
          example: '123456'

      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Player'
          description: Returns player
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorList'
          description: Bad request
        500:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorList'
          description: Internal error


components:
  schemas:
    Players:
      type: object
      properties:
        players:
          type: array
          items:
            $ref: '#/components/schemas/Player'

    Player:
      type: object
      properties:
        id:
          type: string
        firstName:
          type: string
        lastName:
          type: string

    Error:
      properties:
        title:
          type: string
        status:
          type: integer
        detail:
          type: string
      type: object
    ErrorList:
      properties:
        errors:
          description: error
          items:
            $ref: '#/components/schemas/Error'
          type: array
      required:
        - errors
      type: object
