server:
  port: 9000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: players-service
          uri: lb://PLAYERS-SERVICE
          predicates:
            - Path=/players/**
        - id: teams-service
          uri: lb://TEAM-SERVICE
          predicates:
            - Path=/teams/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://discovery:9080}/eureka

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"