server:
  port: 9000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: playersService
          uri: lb://PLAYERS-SERVICE
          predicates:
            - Path=/rest/player/**
        - id: teamService
          uri: lb://TEAM-SERVICE
          predicates:
            - Path=/rest/team/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9080/eureka/
