server:
  port: 9094

spring:
  application:
    name: init-service
  kafka:
    streams:
      competition-application-id: competitions-enriched-stream
      team-application-id: team-enriched-stream
      bootstrap-servers: localhost:19092
    producer:
      bootstrap-servers: localhost:19092
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    bootstrap-servers: localhost:19092
    consumer:
      bootstrap-servers: localhost:19092
      group-id: CompetitionErrorReplyGroupId
      max-poll-records: 1
      enable-auto-commit: false
      auto-offset-reset: earliest

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:9080/eureka/

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

init:
  competitions:
    - FR1
    - FR2
    - FR3
    - GB1
    - GB2
    - GB3
    - L1
    - L2
    - L3
    - IT1
    - IT2
    - ES1
    - ES2
    - PO1
    - PO2